/*
 *  arch/arm/mach-mvt12socfpga/include/mach/regs-uart.h
 *
 *  Copyright (C) 2010 MtekVision Co., Ltd.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
#ifndef __ASM_ARCH_REGS_UART_H
#define __ASM_ARCH_REGS_UART_H

/*
 * UART Registers
 */
#define UART_INT_STATUS			0x00
#define UART_INT_MASK			0x04
#define UART_INT_CLR			0x08
#define UART_BAUDRATE			0x0C
#define UART_CFG				0x10
#define UART_FIFO_STATUS		0x14
#define UART_FIFO_CFG			0x18
#define UART_MODE				0x1C
#define UART_TX_FIFO			0x100
#define UART_RX_FIFO			0x200

/*
 * UART Interrupt = 0x00, 0x04, 0x08
 */
#define UART_INT_RTS_RAW_SHIFT		(12)
#define UART_INT_RTS_RAW_WIDTH		(1)
#define UART_INT_RTS_RAW_MASK		(UART_INT_RTS_RAW_WIDTH \
					<< UART_INT_RTS_RAW_SHIFT)
#define UART_INT_CTS_RAW_SHIFT		(11)
#define UART_INT_CTS_RAW_WIDTH		(1)
#define UART_INT_CTS_RAW_MASK		(UART_INT_CTS_RAW_WIDTH \
					<< UART_INT_CTS_RAW_SHIFT)
#define UART_INT_RX_PUSH_ERR_SHIFT	(10)
#define UART_INT_RX_PUSH_ERR_WIDTH	(1)
#define UART_INT_RX_PUSH_ERR_MASK	(UART_INT_RX_PUSH_ERR_WIDTH \
					<< UART_INT_RX_PUSH_ERR_SHIFT)
#define UART_INT_PARITY_ERR_SHIFT	(9)
#define UART_INT_PARITY_ERR_WIDTH	(1)
#define UART_INT_PARITY_ERR_MASK	(UART_INT_PARITY_ERR_WIDTH \
					<< UART_INT_PARITY_ERR_SHIFT)
#define UART_INT_FRAME_ERR_SHIFT	(8)
#define UART_INT_FRAME_ERR_WIDTH	(1)
#define UART_INT_FRAME_ERR_MASK		(UART_INT_FRAME_ERR_WIDTH \
					<< UART_INT_FRAME_ERR_SHIFT)
#define UART_INT_BUS_POP_ERR_SHIFT	(7)
#define UART_INT_BUS_POP_ERR_WIDTH	(1)
#define UART_INT_BUS_POP_ERR_MASK	(UART_INT_BUS_POP_ERR_WIDTH \
					<< UART_INT_BUS_POP_ERR_SHIFT)
#define UART_INT_BUS_PUSH_ERR_SHIFT	(6)
#define UART_INT_BUS_PUSH_ERR_WIDTH	(1)
#define UART_INT_BUS_PUSH_ERR_MASK	(UART_INT_BUS_PUSH_ERR_WIDTH \
					<< UART_INT_BUS_PUSH_ERR_SHIFT)
#define UART_INT_RX_FF_SHIFT		(5)
#define UART_INT_RX_FF_WIDTH		(1)
#define UART_INT_RX_FF_MASK		(UART_INT_RX_FF_WIDTH \
					<< UART_INT_RX_FF_SHIFT)
#define UART_INT_RX_HF_SHIFT		(4)
#define UART_INT_RX_HF_WIDTH		(1)
#define UART_INT_RX_HF_MASK		(UART_INT_RX_HF_WIDTH \
					<< UART_INT_RX_HF_SHIFT)
#define UART_INT_RX_FE_SHIFT		(3)
#define UART_INT_RX_FE_WIDTH		(1)
#define UART_INT_RX_FE_MASK		(UART_INT_RX_FE_WIDTH \
					<< UART_INT_RX_FE_SHIFT)
#define UART_INT_TX_FF_SHIFT		(2)
#define UART_INT_TX_FF_WIDTH		(1)
#define UART_INT_TX_FF_MASK		(UART_INT_TX_FF_WIDTH \
					<< UART_INT_TX_FF_SHIFT)
#define UART_INT_TX_HF_SHIFT		(1)
#define UART_INT_TX_HF_WIDTH		(1)
#define UART_INT_TX_HF_MASK		(UART_INT_TX_HF_WIDTH \
					<< UART_INT_TX_HF_SHIFT)
#define UART_INT_TX_FE_SHIFT		(0)
#define UART_INT_TX_FE_WIDTH		(1)
#define UART_INT_TX_FE_MASK		(UART_INT_TX_FE_WIDTH \
					<< UART_INT_TX_FE_SHIFT)

/*
 * UART BAUD RATE CONTROL = 0x0C
 */
#define UART_BAUDRATE_RX_DIV_SHIFT	(16)
#define UART_BAUDRATE_RX_DIV_WIDTH	(0xFFFF)
#define UART_BAUDRATE_RX_DIV_MASK	(UART_BAUDRATE_RX_DIV_WIDTH \
					<< UART_BAUDRATE_RX_DIV_SHIFT)
#define UART_BAUDRATE_TX_DIV_SHIFT	(0)
#define UART_BAUDRATE_TX_DIV_WIDTH	(0xFFFF)
#define UART_BAUDRATE_TX_DIV_MASK	(UART_BAUDRATE_TX_DIV_WIDTH \
					<< UART_BAUDRATE_TX_DIV_SHIFT)

/*
 * UART CONFIG = 0x10
 */
#define UART_CFG_RTS_FIFO_LEVEL_SHIFT	(24)
#define UART_CFG_RTS_FIFO_LEVEL_WIDTH	(0xFF)
#define UART_CFG_RTS_FIFO_LEVEL_MASK	(UART_CFG_RTS_FIFO_LEVEL_WIDTH \
					<< UART_CFG_RTS_FIFO_LEVEL_SHIFT)
#define UART_CFG_CTS_ENA_SHIFT		(22)
#define UART_CFG_CTS_ENA_WIDTH		(1)
#define UART_CFG_CTS_ENA_MASK		(UART_CFG_CTS_ENA_WIDTH \
					<< UART_CFG_CTS_ENA_SHIFT)
#define UART_CFG_RTS_ENA_SHIFT		(21)
#define UART_CFG_RTS_ENA_WIDTH		(1)
#define UART_CFG_RTS_ENA_MASK		(UART_CFG_RTS_ENA_WIDTH \
					<< UART_CFG_RTS_ENA_SHIFT)
#define UART_CFG_RX_FIFO_SIZE_SHIFT	(19)
#define UART_CFG_RX_FIFO_SIZE_WIDTH	(0x3)
#define UART_CFG_RX_FIFO_SIZE_MASK	(UART_CFG_RX_FIFO_SIZE_WIDTH \
					<< UART_CFG_RX_FIFO_SIZE_SHIFT)
#define UART_CFG_TX_FIFO_SIZE_SHIFT	(17)
#define UART_CFG_TX_FIFO_SIZE_WIDTH	(0x3)
#define UART_CFG_TX_FIFO_SIZE_MASK	(UART_CFG_TX_FIFO_SIZE_WIDTH \
					<< UART_CFG_TX_FIFO_SIZE_SHIFT)
#define UART_CFG_EXT_PAD_EN_SHIFT	(16)
#define UART_CFG_EXT_PAD_EN_WIDTH	(1)
#define UART_CFG_EXT_PAD_EN_MASK	(UART_CFG_EXT_PAD_EN_WIDTH \
					<< UART_CFG_EXT_PAD_EN_SHIFT)
#define UART_CFG_RX_SAMPLING_POS_SHIFT	(12)
#define UART_CFG_RX_SAMPLING_POS_WIDHT	(0xF)
#define UART_CFG_RX_SAMPLING_POS_MASK	(UART_CFG_RX_SAMPLING_POS_WIDHT \
					<< UART_CFG_RX_SAMPLING_POS_SHIFT)
#define UART_CFG_IR_TX_POL_LOW_SHIFT	(10)
#define UART_CFG_IR_TX_POL_LOW_WIDHT	(1)
#define UART_CFG_IR_TX_POL_LOW_MASK	(UART_CFG_IR_TX_POL_LOW_WIDHT \
					<< UART_CFG_IR_TX_POL_LOW_SHIFT)
#define UART_CFG_IR_RX_POL_LOW_SHIFT	(9)
#define UART_CFG_IR_RX_POL_LOW_WIDHT	(1)
#define UART_CFG_IR_RX_POL_LOW_MASK	(UART_CFG_IR_RX_POL_LOW_WIDHT \
					<< UART_CFG_IR_RX_POL_LOW_SHIFT)
#define UART_CFG_IR_MODE_SHIFT		(8)
#define UART_CFG_IR_MODE_WIDHT		(1)
#define UART_CFG_IR_MODE_MASK		(UART_CFG_IR_MODE_WIDHT \
					<< UART_CFG_IR_MODE_SHIFT)
#define UART_CFG_ECHO_LOOP_EN_SHIFT	(7)
#define UART_CFG_ECHO_LOOP_EN_WIDHT	(1)
#define UART_CFG_ECHO_LOOP_EN_MASK	(UART_CFG_ECHO_LOOP_EN_WIDHT \
					<< UART_CFG_ECHO_LOOP_EN_SHIFT)
#define UART_CFG_REMOTE_LOOP_EN_SHIFT	(6)
#define UART_CFG_REMOTE_LOOP_EN_WIDHT	(1)
#define UART_CFG_REMOTE_LOOP_EN_MASK	(UART_CFG_REMOTE_LOOP_EN_WIDHT \
					<< UART_CFG_REMOTE_LOOP_EN_SHIFT)
#define UART_CFG_LOCAL_LOOP_EN_SHIFT	(5)
#define UART_CFG_LOCAL_LOOP_EN_WIDHT	(1)
#define UART_CFG_LOCAL_LOOP_EN_MASK	(UART_CFG_LOCAL_LOOP_EN_WIDHT \
					<< UART_CFG_LOCAL_LOOP_EN_SHIFT)
#define UART_CFG_RX_ENDIAN_SWAP_SHIFT	(4)
#define UART_CFG_RX_ENDIAN_SWAP_WIDHT	(1)
#define UART_CFG_RX_ENDIAN_SWAP_MASK	(UART_CFG_RX_ENDIAN_SWAP_WIDHT \
					<< UART_CFG_RX_ENDIAN_SWAP_SHIFT)
#define UART_CFG_TX_ENDIAN_SWAP_SHIFT	(3)
#define UART_CFG_TX_ENDIAN_SWAP_WIDHT	(1)
#define UART_CFG_TX_ENDIAN_SWAP_MASK	(UART_CFG_TX_ENDIAN_SWAP_WIDHT \
					<< UART_CFG_TX_ENDIAN_SWAP_SHIFT)
#define UART_CFG_PARITY_SHIFT		(1)
#define UART_CFG_PARITY_WIDHT		(0x3)
#define UART_CFG_PARITY_MASK		(UART_CFG_PARITY_WIDHT \
					<< UART_CFG_PARITY_SHIFT)
#define UART_CFG_2STOP_BITS_SHIFT	(0)
#define UART_CFG_2STOP_BITS_WIDTH	(1)
#define UART_CFG_2STOP_BITS_MASK	(UART_CFG_2STOP_BITS_WIDTH \
					<< UART_CFG_2STOP_BITS_SHIFT)

/*
 * UART FIFO STATUS = 0x14
 */
#define UART_FIFO_STATUS_RX_FLUSH_SHIFT	(31)
#define UART_FIFO_STATUS_RX_FLUSH_WIDTH	(1)
#define UART_FIFO_STATUS_RX_FLUSH_MASK	(UART_FIFO_STATUS_RX_FLUSH_WIDTH \
					<< UART_FIFO_STATUS_RX_FLUSH_SHIFT)
#define UART_FIFO_STATUS_TX_FLUSH_SHIFT	(30)
#define UART_FIFO_STATUS_TX_FLUSH_WIDTH	(1)
#define UART_FIFO_STATUS_TX_FLUSH_MASK	(UART_FIFO_STATUS_TX_FLUSH_WIDTH \
					<< UART_FIFO_STATUS_TX_FLUSH_SHIFT)
#define UART_FIFO_STATUS_RX_CNT_SHIFT	(8)
#define UART_FIFO_STATUS_RX_CNT_WIDTH	(0xFF)
#define UART_FIFO_STATUS_RX_CNT_MASK	(UART_FIFO_STATUS_RX_CNT_WIDTH \
					<< UART_FIFO_STATUS_RX_CNT_SHIFT)
#define UART_FIFO_STATUS_TX_CNT_SHIFT	(0)
#define UART_FIFO_STATUS_TX_CNT_WIDTH	(0xFF)
#define UART_FIFO_STATUS_TX_CNT_MASK	(UART_FIFO_STATUS_TX_CNT_WIDTH \
					<< UART_FIFO_STATUS_TX_CNT_SHIFT)

/*
 * UART FIFO FLAG CONFIGURATION = 0x18
 */
#define UART_FIFO_CFG_RX_HE_SHIFT	(8)
#define UART_FIFO_CFG_RX_HE_WIDTH	(0xFF)
#define UART_FIFO_CFG_RX_HE_MASK	(UART_FIFO_CFG_RX_HE_WIDTH \
					<< UART_FIFO_CFG_RX_HE_SHIFT)
#define UART_FIFO_CFG_TX_HF_SHIFT	(0)
#define UART_FIFO_CFG_TX_HF_WIDTH	(0xFF)
#define UART_FIFO_CFG_TX_HF_MASK	(UART_FIFO_CFG_TX_HF_WIDTH \
					<< UART_FIFO_CFG_TX_HF_SHIFT)

/*
 * UART ADD MODE REGISTER = 0x1C
 */
#define UART_MODE_HS_SHIFT		(4)
#define UART_MODE_HS_WIDTH		(1)
#define UART_MODE_HS_MASK		(UART_MODE_HS_WIDTH \
					<< UART_MODE_HS_SHIFT)
#define UART_MODE_RX_WORD_LEN_SHIFT	(2)
#define UART_MODE_RX_WORD_LEN_WIDTH	(0x3)
#define UART_MODE_RX_WORD_LEN_MASK	(UART_MODE_RX_WORD_LEN_WIDTH \
					<< UART_MODE_RX_WORD_LEN_SHIFT)
#define UART_MODE_TX_WORD_LEN_SHIFT	(0)
#define UART_MODE_TX_WORD_LEN_WIDTH	(0x3)
#define UART_MODE_TX_WORD_LEN_MASK	(UART_MODE_TX_WORD_LEN_WIDTH \
					<< UART_MODE_TX_WORD_LEN_SHIFT)

#endif /* __ASM_ARCH_REGS_UART_H */
