obj-$(CONFIG_ION_MV_VICTORIA) += victoria-socfpga-ion.o \
		 						 victoria-socfpga-ion-device.o

obj-$(CONFIG_ION_MV_MFP7V2000TQ) += mfp7v2000tq-socfpga-ion.o \
		 							mfp7v2000tq-socfpga-ion-device.o
